[Settings]
Framerate=60
; You can put as many Hotkeys as you would like.
; This uses Windows virtual key codes. A list can be found here https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
Hotkey=0x57
Hotkey=0x41
Hotkey=0x53
Hotkey=0x44
Hotkey=0x20